lane :bump_version do |options|
  result = flutter_bump_version(
    parts: options[:bump],
    pubspec: "./pubspec.yaml",
    bump_build: options[:bump_build]
  )
  UI.message(result[:new])
  UI.message(result[:previous])
  # TODO : Uncomment this lines if you want to push new version to git remote
  # if(options[:push])
  #   sh "git config --global user.email m97.chahboun@gmail.com"
  #   sh "git config --global user.name Mohammed chahboun"
  #   sh "git config --global push.followTags true"
  #   sh "git add ../../pubspec.yaml"
  #   sh 'git commit -m "bump version from result[:new] to ' + result[:previous] + ' by fastlane plugin"'
  #   sh 'git tag -a v'+result[:new]+' -m "Version '+result[:new]+'"'
  #   sh "git push origin"
  # end
end
