lane :bump_version do |options|
  current_version = flutter_bump_version(
    parts: options[:bump],
    pubspec: "./pubspec.yaml"
  )
  UI.message(current_version)
  # TODO : Uncomment this lines if you want to push new version to git remote
  # if(options[:push])
  #   sh "git config --global user.email m97.chahboun@gmail.com"
  #   sh "git config --global user.name Mohammed chahboun"
  #   sh "git config --global push.followTags true"
  #   sh "git add ../../pubspec.yaml"
  #   sh 'git commit -m "bump version to ' + current_version + ' from fastlane"'
  #   sh 'git tag -a v'+current_version+' -m "Version '+current_version+'"'
  #   sh "git push origin"
  # end
end
